ExcludeArch: %{ix86}
# Generated by rust2rpm 26
%bcond_without check

%global ver ###
%global commit ###
%global commitdatestring ###
%global commitdate ###

Name:           cosmic-bg-theme
Version:        %{ver}~git%{commitdate}.%{sub %{commit} 1 7}
Release:        %autorelease
Summary:        Unofficial service for syncing COSMIC theme with the active wallpaper

SourceLicense:  GPL-3.0
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/wash2/cosmic_bg_theme

Source:         https://github.com/wash2/cosmic_bg_theme/archive/%{commit}.tar.gz
# To create the below sources:
# * git clone https://github.com/wash2/cosmic_bg_theme at the specified commit
# * cargo vendor > vendor-config.toml
# * tar -pczf vendor.tar.gz vendor
Source:         vendor.tar.gz
# * mv vendor-config.toml ..
Source2:         vendor-config.toml

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rustc
BuildRequires:  lld
BuildRequires:  cargo
BuildRequires:  make

BuildRequires:  systemd-rpm-macros

Requires:       cosmic-bg

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic_bg_theme-%{commit} -p1 -a1
%cargo_prep -N
# Check if .cargo/config.toml exists
if [ -f .cargo/config.toml ]; then
  # If it exists, append the contents of %{SOURCE2} to .cargo/config.toml
  cat %{SOURCE2} >> .cargo/config.toml
  echo "Appended %{SOURCE2} to .cargo/config.toml"
else
  # If it does not exist, append the contents of %{SOURCE2} to .cargo/config
  cat %{SOURCE2} >> .cargo/config
  echo "Appended %{SOURCE2} to .cargo/config"
fi

%build
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
sed 's/\(.*\) (.*#\(.*\))/\1+git\2/' -i cargo-vendor.txt

%install
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
install -Dm0755 target/release/cosmic-bg-theme %{buildroot}/%{_bindir}/cosmic-bg-theme
sed -i "s|ExecStart=.*|ExecStart=%{_bindir}/cosmic-bg-theme|g" cosmic-bg-theme.service
install -Dm0644 cosmic-bg-theme.service %{buildroot}/%{_userunitdir}/cosmic-bg-theme.service

%if %{with check}
%check
# Set vergen environment variables
export VERGEN_GIT_COMMIT_DATE="date --utc '%{commitdatestring}'"
export VERGEN_GIT_SHA="%{commit}"
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/cosmic-bg-theme
%{_userunitdir}/cosmic-bg-theme.service

%changelog
%autochangelog
